### ISSUE TITLE
Repeated functions declarations in lodash

### ISSUE THREAD

**Issue by masaeedu** [joarwilk/flowgen#10]
Not sure where else to bring this up, but regarding the repeated declarations of the same function in the lodash typedefs that you mentioned in the README: those are probably overloads. I'm just starting out with Flow, but [it seems](https://flowtype.org/docs/functions.html#overloading) overloading is supported in Flow as well.

**Comment by sman591** [comment]
Flow does support this: https://github.com/facebook/flow/issues/60

However from what I've observed, `flowgen` does _not_ copy overloaded typescript definitions to Flow; it just copies over the first one 😞

**Comment by MarvinHannott** [comment]
Having the same issue. Overloads are not handled at all. Don't really understand why since overloads are handled in the exact same way in both programming languages.
