### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by ItsAleph** [joarwilk/flowgen#187]
If the TS defenition I have contains `import { ... } from "external-library-from-node_modules";`, will `flowgen` get those defenitions from the `external-...-node_modules` library and put them in the resulting flow libdef?
(asking because afaik flow-typed (and flow itself) does not support `require(...)`ing or `import`ing external libdefs)

**Comment by orta** [comment]
No

**Comment by ItsAleph** [comment]
Sad :(
Maybe this is on the roadmap?

**Comment by ItsAleph** [comment]
ok, i guess it's not.

**Comment by ItsAleph** [comment]
.

**Comment by orta** [comment]
You're welcome to look at adding it
