### ISSUE TITLE
Changing string literal types to type defined types (errors)

### ISSUE THREAD

**Issue by bradennapier** [joarwilk/flowgen#24]
![image](https://user-images.githubusercontent.com/15365418/32150462-5646ca86-bcd0-11e7-8c81-afa110741ea4.png)

In the screenshot above it should have been 'error', 'headers', 'connection' per 

https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/uws/index.d.ts

Simple enough to do manually - just reporting the bug I run into.

**Comment by orta** [comment]
You can start this issue by adding a test for 

```ts
    on(event: 'error', cb: (err: Error) => void): this;
    on(event: 'close', cb: (code: number, message: string) => void): this;
    on(event: 'message', cb: (data: any, flags: { binary: boolean }) => void): this;
    on(event: 'ping', cb: (data: any, flags: { binary: boolean }) => void): this;
    on(event: 'pong', cb: (data: any, flags: { binary: boolean }) => void): this;
    on(event: 'open', cb: () => void): this;
    on(event: string, listener: (...args: any[]) => void): this;
```

And it should not take the string literals and convert them into constants. You can see an example #30 

It's possible this lib doesn't handle string literals well in all places

**Comment by talshani** [comment]
I couldn't reproduce this
I added a test for this case anyway
