### ISSUE TITLE
Odd TS conventions

### ISSUE THREAD

**Issue by InvictusMB** [joarwilk/flowgen#3]
> Lodash has been one of the reference libraries i've worked with when creating the converter. The definition is mostly just a series of interfaces with the same name being re-declared over and over again for each function, which doesn't translate to flow at all. There's multiple ways of solving this but I dont have a great solution for it in place yet.

As per TS Docs they can all be merged together. I assume that's what TS type checker does internally.
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Did I understand correctly the issue?

**Comment by joarwilk** [comment]
Yep, that solved it for interfaces. Still have to figure out overloading functions outside of classes, but its good enough for now (lodash compiles perfectly!)

**Comment by InvictusMB** [comment]
Could you give an example of overloading that doesn't translate into flow properly?

Lodash conversion still doesn't work for me for both v3 and v4 because of #4

**Comment by MarvinHannott** [comment]
> @joarwilk, could you give an example of overloading that doesn't translate into flow properly?

Here is a quick example I have tried:
```ts
declare module atest {
    declare function add(a:number, b:number): number
    declare function add(a:string, b:string): string
}
```
This results in 
```ts
declare module "atest" {
  declare function add(a: number, b: number): number;
}
```
which means only the first declaration gets processed while all following are ignored. Which seems odd since overloads are handled in the same way by multiple declarations.
