### ISSUE TITLE
Replace js-beautify with prettier?

### ISSUE THREAD

**Issue by talshani** [joarwilk/flowgen#42]
I couldn't find any clues if js-beautify is aware of flow syntax, but I am sure that prettier does.
I think replacing js-beautify with prettier will be more flow compliant.

Using it on the codebase to prettify it and force a common code style is also a good idea.
If you think it is a good idea, I have a branch locally I can PR

**Comment by orta** [comment]
Yeah, works for me 👍

**Comment by joarwilk** [comment]
Yes, great idea, I fully support this.
