### ISSUE TITLE
Some node type kinds have no match in TS.SyntaxKind enum

### ISSUE THREAD

**Issue by InvictusMB** [joarwilk/flowgen#6]
[FunctionTypeAnnotation](https://github.com/joarwilk/flowgen/blob/master/src/printers/node.js#L18) is known in Babel AST but not in TS as of v2.1.4

[LastNodeType](https://github.com/joarwilk/flowgen/blob/master/src/printers/node.js#L48) probably typo and should be [LastTypeNode](https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L350)

**Comment by joarwilk** [comment]
Fixed in latest update
