### ISSUE TITLE
No // @flow ?

### ISSUE THREAD

**Issue by benevbright** [joarwilk/flowgen#75]
Hi, I have a quick question.
AFAIK, in order to Flow work, we need ` // @flow` this line on the top.
But it didn't write this line for us?

I used CLI flowgen.
Thanks.

**Comment by orta** [comment]
I don't think it does (at least it didn't for [danger](https://danger.systems/js/) ) but I'm fine with adding it?

**Comment by benevbright** [comment]
Thanks for your response. @orta 
I'm just curious. 
If it doesn't write ` // @flow` line, we can't use this module, can we? 
Am I missing something?

I'm building my module which is written with TS. 
And I want to use that from my react-native App, which is written with JS and Flow.
So, I tried using `flowgen` before publishing the module.

But I can't use it from my app because it doesn't have `// @flow`. If I added myself, it works.

**Comment by orta** [comment]
I'm unsure, it's been a few years since I've used a flow project so maybe things have changed since I first started using this lib?

**Comment by goodmind** [comment]
it is supposed to be used in `flow-typed` directory which doesn't require //@flow at top

**Comment by benevbright** [comment]
Ok, I misunderstood the usage. Thanks guys!
