### ISSUE TITLE
Generated files shouldn't claim authorship by flowgen author

### ISSUE THREAD

**Issue by callumlocke** [joarwilk/flowgen#85]
I'm very grateful for this module and I appreciate the effort that's gone into it, but I think it's potentially confusing to default to including flowgen's own author an repo details in a doc comment at the top of every file it outputs:

```
/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.8.2
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

// ...followed by MY type defs
```

At a glance it seems to claim authorship of the file, which is not the case. (I am just talking about the 'Author' and 'Repo' lines – the rest of the comment is good.)

**Comment by orta** [comment]
Yeah, I think that makes sense - @joarwilk - got an opinion?

**Comment by joarwilk** [comment]
By all means, remove that @orta 

Feels very irrelevant at this stage

**Comment by goodmind** [comment]
@orta so would it just be 
```
/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.8.2
 */
```

?

**Comment by orta** [comment]
Yeah, that works for me 👍

**Comment by techieshark** [comment]
Using flowgen v1.10.0 I can see that this issue is fixed; here's what is atop a flowgen-generated file:

```
