### ISSUE TITLE
Function and namespace declarations are not merged

### ISSUE THREAD

**Issue by karmeleon** [joarwilk/flowgen#88]
Assigning a value to a key in a function is a somewhat common pattern, especially in React for setting `defaultProps` on stateless functional components:
```tsx
import React from 'react';

interface Props: {
    a: number,
    b: string,
};

function Component({a, b}: Props): React.ReactNode {
    return <div>a is {a} and b is {b}</div>;
}

Component.defaultProps = {
    a: 1,
};

export default Component;
```

`tsc` generates something like this as its corresponding `.d.ts` header:

```ts
// this is the callable signature
declare function Component({a, b}: Props): JSX.Element;

// any additional values on the function go here
declare namespace Component {
    var defaultProps: {
        a: number;
    }
}
```

This is valid because of TypeScript's [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) which causes `tsc` to interpret the function and namespace declarations with the same name to mean "this is a function that also has some values in it". Flow does not have this merging, so the correct way to express this concept in Flow typedefs is this:

```ts
declare var Component {
    // this is the callable signature
    (p: Props): React$Node;
    // any additional values on the function go here
    defaultProps: {
        a: number;
    };
}
```

Flowgen generates this instead, which is a pretty faithful translation of the source `.d.ts` file given that Flow doesn't support namespaces:

```ts
// this is the callable signature
declare function Component(x: Props): React$Node;
declare var Component: typeof npm$namespace$Component;

// any additional values on the function go here
declare var npm$namespace$Component: {
    defaultProps: typeof Component$defaultProps;
};
declare var Component$defaultProps: {
    a: number;
};
```

However, this is invalid in Flow and it isn't happy:

```
7: declare function Component(x: Props): React$Node;
                             ^ property `defaultProps` is missing in function type [1] but exists in object type [2].
References:
7: declare function Component(x: Props): React$Node;
                             ^ [1]
8: declare var Component: typeof npm$namespace$Component;
                          ^ [2]
8: declare var Component: typeof npm$namespace$Component;
                          ^ a call signature declaring the expected parameter / return type is missing in object type [1] but exists in function type [2].
References:
8: declare var Component: typeof npm$namespace$Component;
                          ^ [1]
7: declare function Component(x: Props): React$Node;
```
[source tryflow](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQBRge1QZ3gF54BvAKHnigC54A7AVwFsAjEGAbgvhdr0RgBLOgHMuAXy5kA9NKQALQQSUKEYKBGgsICPIJF0oiBnDKhIsBADMGdMIkHY68AMLYmqJyDqIAFAA9aLFw8AEpaACUQKHsAEgA5bFAuc2g4eAA3WFd3TzpvRFoUdGwrelQmWMMmEDxUGJBYtw8vHylZKjpkKmBgQQcnDUyNBlr4J1V4GzsB5xFseHl2EDNwNIQsmHLK6tr6sEbmvILackpKUCsoBghEYPwitBBSnJb8n1jL69v7vAkUtaWYZbI6tRCfEBXG53HAPUjcSg0ejMNicMiSIA)

Flowgen needs to be able to detect when a `.d.ts` file is declaring a function and namespace with the same name and generate a single Flow var declaration that has a callable signature as well as the types of the properties on the function.

**Comment by goodmind** [comment]
Thanks for report! I'll check what can I do with this

**Comment by goodmind** [comment]
#89 should fix this

**Comment by karmeleon** [comment]
Thanks for the quick turnaround! :)
