### ISSUE TITLE
Use $Shape<> for Partial<> instead $Rest<X, {}>

### ISSUE THREAD

**Issue by kevinbarabash** [joarwilk/flowgen#96]
It seems like `$Shape<>` is better match match for `Partial<>`.  I can put together a PR for this.

**Comment by goodmind** [comment]
I removed it specifically because it isn't better match

**Comment by kevinbarabash** [comment]
@goodmind why is `$Rest<X, {}>` a better match?

**Comment by goodmind** [comment]
@kevinbarabash it makes fields optional, while $Shape is weird property matching thing

**Comment by kevinbarabash** [comment]
I didn't realize that.  The docs make `$Shape` sound very simple:
> Copies the shape of the type supplied, but marks every field optional.

**Comment by goodmind** [comment]
Hah, it doesn't do this, related issue https://github.com/facebook/flow/issues/6906

**Comment by goodmind** [comment]
@kevinbarabash can you close this? I don't have rights here
