### ISSUE TITLE
Possible solution for Pick

### ISSUE THREAD

**Issue by kevinbarabash** [joarwilk/flowgen#97]
In https://www.typescriptlang.org/docs/handbook/advanced-types.html, `Pick` is defined as:
```
type Pick<T, K extends keyof T> = {
    [P in K]: T[P];
}
```

Translating this to flow yields:
```
type Pick<T, K: $Keys<T>> = {
    [K]: $ElementType<T, K>,
};
```

[Example](https://flow.org/try/#0C4TwDgpgBAahDGBmKBeKBvAPgKClAHgFxQB2ArgLYBGEATgDS5QjHnV2N4BerlND2TAF8A3NmyhIUAAoBLeAGsAPABV6UANJRiAEg0QQAZ1UA+E6gxM8AbQ0BdXQFEANhAoQSwFeAir1Gk0ZRcUloOHgAJgs5RSVwxHUAInxEqEwoRJBEkzFsAAp0IigAVnUWKABGAAZ1HkrioWJ4gEoxAqLS5mJq2u6GpoQI1vEgA)

**Comment by goodmind** [comment]
https://github.com/lttb/flown

**Comment by kevinbarabash** [comment]
I knew about https://github.com/piotrwitek/utility-types.  It's great to see the same thing in the opposite direction.  Is there any reason not to use `flown` to help `flowgen` add some more ✅the Supported column?

**Comment by goodmind** [comment]
Ah, this is `flowgen` repo, not `flow` 😬

I don't think I can add library to generated files, nor I think your `Pick` is correct, because it makes indexer object

[Counterexample](https://flow.org/try/#0C4TwDgpgBAahDGBmKBeKBvAPgKClAHgFxQB2ArgLYBGEATgDS5QjEDOwtAliQOaN4AvYuWp1GmAL4BubNlCQoABU7wA1gB4AKvSgBpKMQAkuiCFZaAfBdQYmeANq6AukYCiAGwgUIJYJvAQWjq6FozSsvLQcPAATDbKaurRiDoARPipUJhQqSCpFjLYABToRFAArDosUADkNTpCUACM5RLEyQCUMiVllczEdW2wCDFdskA)

**Comment by kevinbarabash** [comment]
That's too bad.  It's because `$ElementType<T, K>` is doing `$ElementType<T, "x" | "y">`.  That's unfortunate.  TypeScript's combination of mapped types and conditional types is really powerful.

**Comment by kevinbarabash** [comment]
> I don't think I can add library to generated files

Is it possible to insert an `import` (or `require`) at the top the generated file?

**Comment by goodmind** [comment]
It wouldn't work with `flow-typed`, because it doesn't support dependencies between packages.

Also `flown` `Pick` doesn't match with typescript one, which uses union, while `flown` uses tuple for keys

**Comment by goodmind** [comment]
Flow utility types are pretty weak, they break too much, TypeScript's mapped + conditional types are more reliable really.
This has to do with lazy evaluation vs eager evaluation, TypeScript uses latter, Flow can't because they have `$Call` which should handle polymorphism lazily

**Comment by goodmind** [comment]
If you're interested in more powerful things just check [my PRs](https://github.com/facebook/flow/pulls?q=is%3Aopen+is%3Apr+label%3AExperiment) about utility types  😀

**Comment by kevinbarabash** [comment]
Wow!  Tuple reduce and tuple spread seem pretty powerful in their own right, but should be even more powerful when used together.
